import React from 'react'
import { useParams } from 'react-router-dom'
import RecipeReviewCard from './card';

const teams = {
    "1":{
        name:"India",
        img:"https://www.wallpapertip.com/wmimgs/241-2413866_indias-mens-cricket-team-world-cup-2019-icc.png",
        description:"On 25th June 1932, the Indian cricket team was granted the status of test playing nation..Virat Kohli is the captain and Rohit Sharma is the vice-captain of the cricket team.",
        more:"Indian cricket team which is sometimes called as ‘Team India’ or ‘Men in Blue’ which plays cricket and is controlled by ‘Board of Control for Cricket in India’ (BCCI).Indian cricket team has given a bunch of talented players like Kapil Dev, Sunil Gavaskar, Sachin Tendulkar, M.S. Dhoni, Virat Kohli, Virendra Sehwag etc.‘Mahendra Singh Dhoni’ is the only player who holds the record of winning all the world titles, i.e. world T20 2007, world cup 2011, ICC Champions Trophy 2013.Indian cricket team had won its first one day world cup in 1983 by defeating the defending champions west indies under the captaincy of Kapil Dev. Indian cricket has won one day world cup titles two times in 1983 and 2011, world t20 in 2007 and ICC champions trophy in 2002 and 2013.The cricket in India started its journey on 25th June 1932 by playing a test match against England. In the beginning, the Indian team was considered as minnows but with the passage of time and with the advancement in cricket, the quality and level of the game of team India have changed totally. Today team India is considered one of the dangerous sides which can snatch the chances of winning from their opponent’s hands at any moment of time."
    },
    "2":{
        name:"Australia",
        img:"https://www.wallpapertip.com/wmimgs/50-509738_australian-cricket-team-australia-2019-world-cup-team.jpg",
        description:"In 1868, a team consisting of Aboriginal cricketers became the first Australian team to tour England.Australia is the most successful team in ODI cricket history, winning more than 60 per cent of their matches, with a record seven World Cup final appearances.",
        more:"The team has played 958 ODI matches, winning 581, losing 334, tying 9 and with 34 ending in a no-result.As of January 2021, Australia is ranked fourth in the ICC ODI Championship on 111 rating points, though have been ranked first for 141 of 185 months since its introduction in 2002. Australia is the most successful team in ODI cricket history, winning more than 60 per cent of their matches, with a record seven World Cup final appearances (1975, 1987, 1996, 1999, 2003, 2007 and 2015) and have won the World Cup a record five times: 1987, 1999, 2003, 2007 and 2015. Australia is the first (and only) team to appear in four consecutive World Cup finals (1996, 1999, 2003 and 2007), surpassing the old record of three consecutive World Cup appearances by the West Indies (1975, 1979 and 1983) and the first and only team to win 3 consecutive World Cups (1999, 2003 and 2007). The team was undefeated in 34 consecutive World Cup matches until the 2011 Cricket World Cup where Pakistan beat them by 4 wickets in the Group stage. It is also the second team to win a World Cup (2015) on home soil, after India (2011). Australia have also won the ICC Champions Trophy twice (2006 and 2009) making them the first and the only team to become back to back winners in the Champions Trophy tournaments. Australia is the only team to win 5 Cricket World Cups, no other team has won more than 2 Cricket World Cups at most."
    },
    "3":{
        name:"England",
        img:"https://www.wallpapertip.com/wmimgs/241-2414300_england-cricket-for-1920-x-1080-hdtv-1080p.jpg",
        description:"he England cricket team represents England and Wales in international cricket. Since 1997, it has been governed by the England and Wales Cricket Board (ECB), having been previously governed by Marylebone Cricket Club (the MCC) since 1903.",
        more:"England, as a founding nation, is a Full Member of the International Cricket Council (ICC) with Test, One Day International (ODI) and Twenty20 International (T20I) status. Until the 1990s, Scottish and Irish players also played for England as those countries were not yet ICC members in their own right.England and Australia were the first teams to play a Test match (15–19 March 1877), and along with South Africa, these nations formed the Imperial Cricket Conference (the predecessor to today's International Cricket Council) on 15 June 1909. England and Australia also played the first ODI on 5 January 1971. England's first T20I was played on 13 June 2005, once more against Australia.In Test series against Australia, England play for The Ashes, one of the most famous trophies in all of sport, and they have won the urn on 32 occasions. England have also played 760 ODIs, winning 383.They have appeared in the final of the Cricket World Cup four times, winning once in 2019; they have also finished as runners-up in two ICC Champions Trophies (2004 and 2013). England have played 136 T20Is, winning 70.As of 18 July 2021, England have played 1,036 Test matches, winning 377 and losing 309 (with 350 draws)."
    },
    "4":{
        name:"Pakistan",
        img:"https://www.wallpapertip.com/wmimgs/241-2411182_cricket-wallpaper-free-download-pakistan-cricket-hd.jpg",
        description:"The Pakistan national cricket team, popularly referred to as the Shaheens Green Shirts, Men in Green, and Cornered Tigers is administered by the Pakistan Cricket Board (PCB). The team is a Full Member of the International Cricket Council, and participates in Test, One Day International (ODI) and Twenty20 International cricket matches.",
        more:"Pakistan has played 437 Test matches, winning 142, losing 133 and drawing 162. Pakistan was given Test status on 28 July 1952, following a recommendation by India, and made its Test debut against India at Feroz Shah Kotla Ground, Delhi, in October 1952, with India winning by an innings and 70 runs.Pakistan has the distinct achievement of having won each of the major ICC international cricket tournaments: ICC Cricket World Cup, ICC World Twenty20, and ICC Champions Trophy; as well as the ninth team who lifting mace of ICC Test Championship.The team is considered a strong but unpredictable team. Traditionally Pakistani cricket has been composed of talented players but is alleged to display limited discipline on occasion, making their performance inconsistent at times. In particular, the India-Pakistan cricket rivalry is usually emotionally charged and can provide for intriguing contests, as talented teams and players from both sides of the border seek to elevate their game to new levels. Pakistan team contests with India in the Cricket World Cup have resulted in packed stadiums and highly charged atmospheres. The team is well supported at home and abroad, especially in the United Kingdom where British Pakistanis have formed a fan-club called the Stani Army. Members of the club show up to matches across the country and are known to provide raucous support. "
    },
    "5":{
        name:"Bangladesh",
        img:"https://www.wallpapertip.com/wmimgs/18-181175_sabash-bangladesh-cricket-team.jpg",
        description:"It is a Full Member of the International Cricket Council (ICC) with Test, One-Day International (ODI) and T20 International (T20I) status. It played its first Test match in November 2000 against India in Dhaka, becoming the tenth Test-playing nation",
        more:"Bangladesh's first official foray into international cricket came in the 1979 ICC Trophy in England. On 31 March 1986, Bangladesh played its first ODI match, against Pakistan in the Asia Cup. For a long time, football was the most popular sport in Bangladesh, but cricket gradually became very popular – particularly in urban areas – and by the late 1990s had surpassed football.In 1997, Bangladesh won the ICC Trophy in Malaysia and thus qualified for its first Cricket World Cup to participate in England in 1999. There, it defeated Pakistan – causing much upset – and also Scotland. On 26 June 2000, Bangladesh was granted full ICC membership.Bangladesh holds the record for most consecutive losses in Tests (21, between 2000 and 2002) and ODIs (23, between 2001 and 2004). After gaining Full Member status with the ICC, Bangladesh had to wait until 2004 for its first ODI win since the 1999 World Cup. The team on the losing side on that occasion was Zimbabwe, who also participated in Bangladesh's maiden Test victory in 2005; by securing a draw in the second match, Bangladesh won their first Test series. In 2009 Bangladesh toured the West Indies for two Tests and by winning both secured their first overseas Test series victory. They then came back to the Caribbean in 2014 for another 2 match test series and the West Indies claimed revenge on Bangladesh for that 2-test series loss that they gave them 5 years earlier by defeating in both test matches."
    },
    "6":{
        name:"New Zealand",
        img:"https://www.wallpapertip.com/wmimgs/21-210244_brendon-mccullum-famous-new-zealand-cricket-player-cricketers.jpg",
        description:"The New Zealand national cricket team represents New Zealand in men's international cricket. Nicknamed the Black Caps, they played their first Test in 1930 against England in Christchurch, becoming the fifth country to play Test cricket. From 1930 New Zealand had to wait until 1956, more than 26 years, for its first Test victory, against the West Indies at Eden Park in Auckland.",
        more:"As of 10 March 2021, New Zealand have played 1360 international matches, winning 524, losing 611, tying 15 and drawing 166 matches while 44 matches ended as no result. The team is ranked 1st in Tests, 1st in ODIs and 3rd in T20Is by the ICC. New Zealand have reached two World Cup finals, in 2015 and 2019. They defeated South Africa in the semi final of the 2015 World Cup, which was their first win in the a world cup semi final, but they ultimately lost to Trans-Tasman rivals Australia. In the next World Cup in 2019, New Zealand again reached the final which they lost to the hosts England on boundary count after the match and the subsequent Super Over both ended as ties.The New Zealand cricket team became known as the Blackcaps in January 1998, after its sponsor at the time, Clear Communications, held a competition to choose a name for the team. This is one of many national team nicknames related to the All Blacks."
    }
};

export const TeamsDetails = () => {
    const {TeamID} = useParams();
    const product = teams[TeamID];
    const {name, description, img, more} = product;
    return (
        <div style={{display:'flex', justifyContent:'center'}}>
            <RecipeReviewCard name={name} desc={description} img={img} more={more}/>
        </div>
    )
}
